import { createFileRoute, useNavigate } from "@tanstack/react-router";
import { useState } from "react";
import { Loader2 } from "lucide-react";
import { AuthShell, FormAlert, PasswordField, PasswordRequirements } from "@/components/portal";
import { Button } from "@/components/ui/button";
import { UserType } from "@/lib/mock-portal";

export const Route = createFileRoute("/create-password")({ validateSearch: (search: Record<string, unknown>) => ({ type: search.type === "staff" ? "staff" as UserType : "student" as UserType }), head: () => ({ meta: [{ title: "Create Password — University of Ilesa Wi-Fi" }, { name: "description", content: "Secure your University of Ilesa Wi-Fi portal account." }, { property: "og:title", content: "Create Your Portal Password" }, { property: "og:description", content: "Set a secure password for your university Wi-Fi account." }, { property: "og:type", content: "website" }, { name: "twitter:card", content: "summary_large_image" }] }), component: CreatePasswordPage });
function CreatePasswordPage() { const { type } = Route.useSearch(); const navigate = useNavigate(); const [password, setPassword] = useState(""); const [confirm, setConfirm] = useState(""); const [error, setError] = useState(false); const [loading, setLoading] = useState(false); const valid = password.length >= 8 && /[a-z]/.test(password) && /[A-Z]/.test(password) && /\d/.test(password) && /[^A-Za-z0-9]/.test(password) && password === confirm; const submit = () => { if (!valid) { setError(true); return; } setLoading(true); window.setTimeout(() => void navigate({ to: "/registration-success", search: { type } }), 700); }; return <AuthShell step="Step 3 of 3"><div className="mb-7"><p className="mb-2 text-sm font-semibold text-primary">Secure your account</p><h1 className="text-3xl font-semibold">Create your password</h1><p className="mt-2 text-sm leading-6 text-muted-foreground">Create a password you’ll use to sign in to the Wi-Fi portal.</p></div><div className="space-y-5">{error && <FormAlert title="Password needs attention">Meet all requirements and make sure both passwords match.</FormAlert>}<PasswordField id="new-password" label="Password" value={password} onChange={(value) => { setPassword(value); setError(false); }} placeholder="Create a password" /><PasswordRequirements password={password} /><PasswordField id="confirm-password" label="Confirm password" value={confirm} onChange={(value) => { setConfirm(value); setError(false); }} placeholder="Enter password again" /><Button className="h-11 w-full" onClick={submit} disabled={loading}>{loading ? <><Loader2 className="animate-spin" />Creating account...</> : "Create Account"}</Button></div></AuthShell>; }
