import { createFileRoute, Link } from "@tanstack/react-router";
import { KeyRound, ShieldCheck, UserRound, Wifi } from "lucide-react";
import { useState } from "react";
import { CredentialCard, PageHeading, PendingCredential, PortalShell, StatusBadge } from "@/components/portal";
import { Button } from "@/components/ui/button";
import { students, UserType, wifiCredential } from "@/lib/mock-portal";

export const Route = createFileRoute("/dashboard")({ validateSearch: (search: Record<string, unknown>) => ({ type: search["type"] === "staff" ? "staff" as UserType : "student" as UserType }), head: () => ({ meta: [{ title: "Dashboard — University of Ilesa Wi-Fi" }, { name: "description", content: "View your University of Ilesa Wi-Fi account and credential status." }, { property: "og:title", content: "University Wi-Fi Dashboard" }, { property: "og:description", content: "Your secure University of Ilesa Wi-Fi account overview." }, { property: "og:type", content: "website" }, { name: "twitter:card", content: "summary_large_image" }] }), component: DashboardPage });
function DashboardPage() { const { type } = Route.useSearch(); const user = students[type]; const [assigned, setAssigned] = useState(true); return <PortalShell user={user}><PageHeading title={`Good morning, ${user.firstName}`} description="Here’s the information associated with your Wi-Fi account." badge={<StatusBadge>Wi-Fi Account Active</StatusBadge>} />{assigned ? <CredentialCard user={user} /> : <PendingCredential />}<div className="mt-4 flex justify-end"><Button variant="ghost" size="sm" onClick={() => setAssigned((value) => !value)} className="text-xs text-muted-foreground">Preview {assigned ? "pending" : "assigned"} state</Button></div><section className="mt-8"><div className="mb-4 flex items-center justify-between"><h2 className="text-lg font-semibold">How to connect</h2><Link to="/help" className="text-sm font-semibold text-primary hover:underline">Need help connecting?</Link></div><div className="grid overflow-hidden rounded-xl border bg-card md:grid-cols-3">{[["01","Open Wi-Fi settings","Open Wi-Fi settings on your device."],["02","Choose the network",`Select ${wifiCredential.network} from the list.`],["03","Enter credentials","Use the username and password shown above."]].map(([number,title,text], index) => <div key={number} className={`p-5 ${index < 2 ? "border-b md:border-b-0 md:border-r" : ""}`}><span className="text-xs font-bold text-primary">{number}</span><h3 className="mt-3 text-sm font-semibold">{title}</h3><p className="mt-1 text-sm leading-6 text-muted-foreground">{text}</p></div>)}</div></section><section className="mt-8 grid gap-4 md:grid-cols-3"><InfoCard icon={ShieldCheck} title="Account Status" value="Active" description="Your account is currently active." /><InfoCard icon={KeyRound} title="Credential Status" value={assigned ? "Assigned" : "Preparing"} description={assigned ? "Your Wi-Fi credential is assigned to you." : "Assignment is currently in progress."} /><InfoCard icon={UserRound} title="Account Type" value={type === "student" ? "Student" : "Staff"} description={`Verified ${type} account.`} /></section></PortalShell>; }
function InfoCard({ icon: Icon, title, value, description }: { icon: typeof Wifi; title: string; value: string; description: string }) { return <div className="rounded-xl border bg-card p-5 shadow-soft"><div className="flex items-center gap-3"><span className="grid size-9 place-items-center rounded-lg bg-primary/8 text-primary"><Icon className="size-4" /></span><div><p className="text-xs font-medium text-muted-foreground">{title}</p><p className="mt-0.5 text-sm font-semibold">{value}</p></div></div><p className="mt-4 text-sm text-muted-foreground">{description}</p></div>; }
