/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CreatePasswordRouteImport } from './routes/create-password'
import { Route as CredentialsRouteImport } from './routes/credentials'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as HelpRouteImport } from './routes/help'
import { Route as LoginVerifyRouteImport } from './routes/login-verify'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as RegistrationSuccessRouteImport } from './routes/registration-success'
import { Route as VerifyRouteImport } from './routes/verify'
import { Route as AdminAuditLogsRouteImport } from './routes/admin/audit-logs'
import { Route as AdminCredentialsRouteImport } from './routes/admin/credentials'
import { Route as AdminDashboardRouteImport } from './routes/admin/dashboard'
import { Route as AdminLoginRouteImport } from './routes/admin/login'
import { Route as AdminProfileRouteImport } from './routes/admin/profile'
import { Route as AdminReportsRouteImport } from './routes/admin/reports'
import { Route as AdminWifiUsersRouteImport } from './routes/admin/wifi-users'
import { Route as SuperAdminAdminsRouteImport } from './routes/super-admin/admins'
import { Route as SuperAdminDashboardRouteImport } from './routes/super-admin/dashboard'
import { Route as SuperAdminSettingsRouteImport } from './routes/super-admin/settings'
import { Route as AdminUsersIndexRouteImport } from './routes/admin/users/index'
import { Route as AdminUsersUserIdRouteImport } from './routes/admin/users/$userId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CreatePasswordRoute = CreatePasswordRouteImport.update({
  id: '/create-password',
  path: '/create-password',
  getParentRoute: () => rootRouteImport,
} as any)
const CredentialsRoute = CredentialsRouteImport.update({
  id: '/credentials',
  path: '/credentials',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const HelpRoute = HelpRouteImport.update({
  id: '/help',
  path: '/help',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginVerifyRoute = LoginVerifyRouteImport.update({
  id: '/login-verify',
  path: '/login-verify',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const RegistrationSuccessRoute = RegistrationSuccessRouteImport.update({
  id: '/registration-success',
  path: '/registration-success',
  getParentRoute: () => rootRouteImport,
} as any)
const VerifyRoute = VerifyRouteImport.update({
  id: '/verify',
  path: '/verify',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminAuditLogsRoute = AdminAuditLogsRouteImport.update({
  id: '/admin/audit-logs',
  path: '/admin/audit-logs',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminCredentialsRoute = AdminCredentialsRouteImport.update({
  id: '/admin/credentials',
  path: '/admin/credentials',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminDashboardRoute = AdminDashboardRouteImport.update({
  id: '/admin/dashboard',
  path: '/admin/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/admin/login',
  path: '/admin/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminProfileRoute = AdminProfileRouteImport.update({
  id: '/admin/profile',
  path: '/admin/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminReportsRoute = AdminReportsRouteImport.update({
  id: '/admin/reports',
  path: '/admin/reports',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminWifiUsersRoute = AdminWifiUsersRouteImport.update({
  id: '/admin/wifi-users',
  path: '/admin/wifi-users',
  getParentRoute: () => rootRouteImport,
} as any)
const SuperAdminAdminsRoute = SuperAdminAdminsRouteImport.update({
  id: '/super-admin/admins',
  path: '/super-admin/admins',
  getParentRoute: () => rootRouteImport,
} as any)
const SuperAdminDashboardRoute = SuperAdminDashboardRouteImport.update({
  id: '/super-admin/dashboard',
  path: '/super-admin/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const SuperAdminSettingsRoute = SuperAdminSettingsRouteImport.update({
  id: '/super-admin/settings',
  path: '/super-admin/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminUsersIndexRoute = AdminUsersIndexRouteImport.update({
  id: '/admin/users/',
  path: '/admin/users/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminUsersUserIdRoute = AdminUsersUserIdRouteImport.update({
  id: '/admin/users/$userId',
  path: '/admin/users/$userId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/create-password': typeof CreatePasswordRoute
  '/credentials': typeof CredentialsRoute
  '/dashboard': typeof DashboardRoute
  '/help': typeof HelpRoute
  '/login-verify': typeof LoginVerifyRoute
  '/profile': typeof ProfileRoute
  '/register': typeof RegisterRoute
  '/registration-success': typeof RegistrationSuccessRoute
  '/verify': typeof VerifyRoute
  '/admin/audit-logs': typeof AdminAuditLogsRoute
  '/admin/credentials': typeof AdminCredentialsRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/profile': typeof AdminProfileRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/wifi-users': typeof AdminWifiUsersRoute
  '/super-admin/admins': typeof SuperAdminAdminsRoute
  '/super-admin/dashboard': typeof SuperAdminDashboardRoute
  '/super-admin/settings': typeof SuperAdminSettingsRoute
  '/admin/users/$userId': typeof AdminUsersUserIdRoute
  '/admin/users/': typeof AdminUsersIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/create-password': typeof CreatePasswordRoute
  '/credentials': typeof CredentialsRoute
  '/dashboard': typeof DashboardRoute
  '/help': typeof HelpRoute
  '/login-verify': typeof LoginVerifyRoute
  '/profile': typeof ProfileRoute
  '/register': typeof RegisterRoute
  '/registration-success': typeof RegistrationSuccessRoute
  '/verify': typeof VerifyRoute
  '/admin/audit-logs': typeof AdminAuditLogsRoute
  '/admin/credentials': typeof AdminCredentialsRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/profile': typeof AdminProfileRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/wifi-users': typeof AdminWifiUsersRoute
  '/super-admin/admins': typeof SuperAdminAdminsRoute
  '/super-admin/dashboard': typeof SuperAdminDashboardRoute
  '/super-admin/settings': typeof SuperAdminSettingsRoute
  '/admin/users/$userId': typeof AdminUsersUserIdRoute
  '/admin/users': typeof AdminUsersIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/create-password': typeof CreatePasswordRoute
  '/credentials': typeof CredentialsRoute
  '/dashboard': typeof DashboardRoute
  '/help': typeof HelpRoute
  '/login-verify': typeof LoginVerifyRoute
  '/profile': typeof ProfileRoute
  '/register': typeof RegisterRoute
  '/registration-success': typeof RegistrationSuccessRoute
  '/verify': typeof VerifyRoute
  '/admin/audit-logs': typeof AdminAuditLogsRoute
  '/admin/credentials': typeof AdminCredentialsRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/profile': typeof AdminProfileRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/wifi-users': typeof AdminWifiUsersRoute
  '/super-admin/admins': typeof SuperAdminAdminsRoute
  '/super-admin/dashboard': typeof SuperAdminDashboardRoute
  '/super-admin/settings': typeof SuperAdminSettingsRoute
  '/admin/users/$userId': typeof AdminUsersUserIdRoute
  '/admin/users/': typeof AdminUsersIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/create-password'
    | '/credentials'
    | '/dashboard'
    | '/help'
    | '/login-verify'
    | '/profile'
    | '/register'
    | '/registration-success'
    | '/verify'
    | '/admin/audit-logs'
    | '/admin/credentials'
    | '/admin/dashboard'
    | '/admin/login'
    | '/admin/profile'
    | '/admin/reports'
    | '/admin/wifi-users'
    | '/super-admin/admins'
    | '/super-admin/dashboard'
    | '/super-admin/settings'
    | '/admin/users/$userId'
    | '/admin/users/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/create-password'
    | '/credentials'
    | '/dashboard'
    | '/help'
    | '/login-verify'
    | '/profile'
    | '/register'
    | '/registration-success'
    | '/verify'
    | '/admin/audit-logs'
    | '/admin/credentials'
    | '/admin/dashboard'
    | '/admin/login'
    | '/admin/profile'
    | '/admin/reports'
    | '/admin/wifi-users'
    | '/super-admin/admins'
    | '/super-admin/dashboard'
    | '/super-admin/settings'
    | '/admin/users/$userId'
    | '/admin/users'
  id:
    | '__root__'
    | '/'
    | '/create-password'
    | '/credentials'
    | '/dashboard'
    | '/help'
    | '/login-verify'
    | '/profile'
    | '/register'
    | '/registration-success'
    | '/verify'
    | '/admin/audit-logs'
    | '/admin/credentials'
    | '/admin/dashboard'
    | '/admin/login'
    | '/admin/profile'
    | '/admin/reports'
    | '/admin/wifi-users'
    | '/super-admin/admins'
    | '/super-admin/dashboard'
    | '/super-admin/settings'
    | '/admin/users/$userId'
    | '/admin/users/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CreatePasswordRoute: typeof CreatePasswordRoute
  CredentialsRoute: typeof CredentialsRoute
  DashboardRoute: typeof DashboardRoute
  HelpRoute: typeof HelpRoute
  LoginVerifyRoute: typeof LoginVerifyRoute
  ProfileRoute: typeof ProfileRoute
  RegisterRoute: typeof RegisterRoute
  RegistrationSuccessRoute: typeof RegistrationSuccessRoute
  VerifyRoute: typeof VerifyRoute
  AdminAuditLogsRoute: typeof AdminAuditLogsRoute
  AdminCredentialsRoute: typeof AdminCredentialsRoute
  AdminDashboardRoute: typeof AdminDashboardRoute
  AdminLoginRoute: typeof AdminLoginRoute
  AdminProfileRoute: typeof AdminProfileRoute
  AdminReportsRoute: typeof AdminReportsRoute
  AdminWifiUsersRoute: typeof AdminWifiUsersRoute
  SuperAdminAdminsRoute: typeof SuperAdminAdminsRoute
  SuperAdminDashboardRoute: typeof SuperAdminDashboardRoute
  SuperAdminSettingsRoute: typeof SuperAdminSettingsRoute
  AdminUsersUserIdRoute: typeof AdminUsersUserIdRoute
  AdminUsersIndexRoute: typeof AdminUsersIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/create-password': {
      id: '/create-password'
      path: '/create-password'
      fullPath: '/create-password'
      preLoaderRoute: typeof CreatePasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/credentials': {
      id: '/credentials'
      path: '/credentials'
      fullPath: '/credentials'
      preLoaderRoute: typeof CredentialsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/help': {
      id: '/help'
      path: '/help'
      fullPath: '/help'
      preLoaderRoute: typeof HelpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login-verify': {
      id: '/login-verify'
      path: '/login-verify'
      fullPath: '/login-verify'
      preLoaderRoute: typeof LoginVerifyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/registration-success': {
      id: '/registration-success'
      path: '/registration-success'
      fullPath: '/registration-success'
      preLoaderRoute: typeof RegistrationSuccessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/verify': {
      id: '/verify'
      path: '/verify'
      fullPath: '/verify'
      preLoaderRoute: typeof VerifyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/audit-logs': {
      id: '/admin/audit-logs'
      path: '/admin/audit-logs'
      fullPath: '/admin/audit-logs'
      preLoaderRoute: typeof AdminAuditLogsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/credentials': {
      id: '/admin/credentials'
      path: '/admin/credentials'
      fullPath: '/admin/credentials'
      preLoaderRoute: typeof AdminCredentialsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/dashboard': {
      id: '/admin/dashboard'
      path: '/admin/dashboard'
      fullPath: '/admin/dashboard'
      preLoaderRoute: typeof AdminDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/login': {
      id: '/admin/login'
      path: '/admin/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/profile': {
      id: '/admin/profile'
      path: '/admin/profile'
      fullPath: '/admin/profile'
      preLoaderRoute: typeof AdminProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/reports': {
      id: '/admin/reports'
      path: '/admin/reports'
      fullPath: '/admin/reports'
      preLoaderRoute: typeof AdminReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/wifi-users': {
      id: '/admin/wifi-users'
      path: '/admin/wifi-users'
      fullPath: '/admin/wifi-users'
      preLoaderRoute: typeof AdminWifiUsersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/super-admin/admins': {
      id: '/super-admin/admins'
      path: '/super-admin/admins'
      fullPath: '/super-admin/admins'
      preLoaderRoute: typeof SuperAdminAdminsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/super-admin/dashboard': {
      id: '/super-admin/dashboard'
      path: '/super-admin/dashboard'
      fullPath: '/super-admin/dashboard'
      preLoaderRoute: typeof SuperAdminDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/super-admin/settings': {
      id: '/super-admin/settings'
      path: '/super-admin/settings'
      fullPath: '/super-admin/settings'
      preLoaderRoute: typeof SuperAdminSettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/users/': {
      id: '/admin/users/'
      path: '/admin/users'
      fullPath: '/admin/users/'
      preLoaderRoute: typeof AdminUsersIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/users/$userId': {
      id: '/admin/users/$userId'
      path: '/admin/users/$userId'
      fullPath: '/admin/users/$userId'
      preLoaderRoute: typeof AdminUsersUserIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CreatePasswordRoute: CreatePasswordRoute,
  CredentialsRoute: CredentialsRoute,
  DashboardRoute: DashboardRoute,
  HelpRoute: HelpRoute,
  LoginVerifyRoute: LoginVerifyRoute,
  ProfileRoute: ProfileRoute,
  RegisterRoute: RegisterRoute,
  RegistrationSuccessRoute: RegistrationSuccessRoute,
  VerifyRoute: VerifyRoute,
  AdminAuditLogsRoute: AdminAuditLogsRoute,
  AdminCredentialsRoute: AdminCredentialsRoute,
  AdminDashboardRoute: AdminDashboardRoute,
  AdminLoginRoute: AdminLoginRoute,
  AdminProfileRoute: AdminProfileRoute,
  AdminReportsRoute: AdminReportsRoute,
  AdminWifiUsersRoute: AdminWifiUsersRoute,
  SuperAdminAdminsRoute: SuperAdminAdminsRoute,
  SuperAdminDashboardRoute: SuperAdminDashboardRoute,
  SuperAdminSettingsRoute: SuperAdminSettingsRoute,
  AdminUsersUserIdRoute: AdminUsersUserIdRoute,
  AdminUsersIndexRoute: AdminUsersIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
